---
name: Test

on:
  - push

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.extract.outputs.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract environment
        id: extract
        run: >
          if [[ ${{ github.event_name }} == 'push' ]];
          then echo "##[set-output name=env;]$(echo ${GITHUB_REF#refs/heads/})";
          else echo "##[set-output name=env;]$(echo ${{github.event.client_payload.env}})";
          fi

  print:
    runs-on: ubuntu-latest
    needs: determine-environment
    steps:
      - name: Print
        if: ${{ github.ref == 'refs/heads/test' }}
        run: echo "executed"

  auto-merge:
    runs-on: ubuntu-latest
    needs: determine-environment
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure git
        run: |
          git --version
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git fetch --all --tags
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

      - name: Merge
        shell: bash
        run: |
          git checkout -b ${{ github.ref == 'refs/heads/test' && 'si' || 'main' }} || git checkout ${{ github.ref == 'refs/heads/test' && 'si' || 'main' }}
          git merge ${{ github.ref == 'refs/heads/test' && 'test' || 'si' }} --ff-only
          git push origin ${{ github.ref == 'refs/heads/test' && 'si' || 'main' }} --force
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}