# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
      - test
      - si
  repository_dispatch:
    types:
      - main
      - test
      - si
      
jobs:
  build:
    environment: ${{ github.event.client_payload.ref == '' && ${github.ref##*/} }} 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Run a one-line script
        run: |
          echo "${{ github.event }}"
          echo "${{ github.event.client_payload.ref }}"
          echo "${{ github.ref }}"
          echo "stage $ECHO!"
        env:
          ECHO: ${{secrets.ECHO}}