# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
      - test
  repository_dispatch:
    types:
      - main
      - test
      
jobs:
  build:
    environment: ${{ github.event.client_payload.ref }} 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Run a one-line script
        run: echo Hello, world!