# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
      - test
      - si
  repository_dispatch:
    types:
      - main
      - test
      - si
      
jobs:
  build:
    environment: ${{ github.event.client_payload.ref == '' && github.ref || github.event.client_payload.ref }} 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Run a one-line script
        shell: bash
        run: |
          echo "teeeeeeessssst"
          echo "si gets this change next"
          echo "${{ github.event }}"
          echo "${{ github.branch }}"
          echo "${{ github.event.client_payload.ref }}"
          echo "${{ github.ref }}"
          if [ "$ECHO" == "si" ]; then echo "si"; else echo "test"; fi
        env:
          ECHO: ${{secrets.ECHO}}