# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
      - test
      - si
  repository_dispatch:
    types:
      - main
      - test
      - si
      
jobs:
  build:
    environment: ${{ github.event.client_payload.environment == '' && github.ref || github.event.client_payload.environment }} 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Run a one-line script
        shell: bash
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Is repository_dispatch: ${{ github.event_name == repository_dispatch }}"
          echo "Is push: ${{ github.event_name == push }}"
          echo "Event: ${{ github.event }}"
          echo "Is repository_dispatch: ${{ github.event == repository_dispatch }}"
          echo "Is push: ${{ github.event == push }}"
          echo "-------------------"
          echo "Branch: ${{ github.branch }}"
          echo "${github.ref#refs/heads/}"
          echo "Branch: ${GITHUB_REF#refs/heads/}"
          echo "${{ github.event.client_payload.ref }}"
          echo "${{ github.ref }}"
          if [ "$ECHO" == "si" ]; then echo "si"; else echo "test"; fi
        env:
          ECHO: ${{secrets.ECHO}}