# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
      - test
      - si
  repository_dispatch:
    types:
      - main
      - test
      - si
      
jobs:
  build:
    environment: ${{ github.event.client_payload.environment == '' && github.ref || github.event.client_payload.environment }} 
    runs-on: ubuntu-latest

    steps:
      - uses: hmarr/debug-action@v2

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}


      - name: Run push
        if: github.event_name == 'push'
        shell: bash
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Event: ${{ github.event }}"
          echo "Ref: ${{ github.ref }}"
          echo "Branch: ${{ github.branch }}"
          echo "${{ github.ref#refs/heads/ }}"
          echo "Branch: ${{ GITHUB_REF#refs/heads/ }}"
          echo "${{ github.event.client_payload }}"
        env:
          ECHO: ${{secrets.ECHO}}
      
      - name: Run dispatch
        if: github.event_name == 'repository_dispatch'
        shell: bash
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Event: ${{ github.event. }}"
          echo "Ref: ${{ github.ref }}"
          echo "Branch: ${{ github.branch }}"
          echo "${github.ref#refs/heads/}"
          echo "Branch: ${GITHUB_REF#refs/heads/}"
          echo "${{ github.event.client_payload.ref }}"
        env:
          ECHO: ${{secrets.ECHO}}