name: Test

on:
  - push

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: echo "run tests"

  develop:
    needs: test
    uses: russoale/action-test/.github/workflows/deploy.yml@test
    with:
      env: develop
      branch: develop
      e2e: true
  
  alpha:
    needs: develop
    uses: russoale/action-test/.github/workflows/deploy.yml@test
    with:
      env: alpha
      branch: alpha
      e2e: false

  beta:
    needs: alpha
    uses: russoale/action-test/.github/workflows/deploy.yml@test
    with:
      env: beta
      branch: beta
      e2e: true
