name: Test

on:
  - push

jobs:

  extract:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract.outputs.branch }}
    steps:
      - name: Extract branch name
        id: extract
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: echo "run tests"

  develop:
    needs: [ extract ]
    if: needs.extract.outputs.branch == 'develop'
    uses: russoale/action-test/.github/workflows/deploy.yml@test
    with:
      sha: ${{ github.sha }}
      env: develop
  
  alpha:
    needs: [ extract, test]
    uses: russoale/action-test/.github/workflows/deploy.yml@test
    with:
      sha: ${{ github.sha }}
      env: alpha
      e2e: true

  beta:
    needs: [ extract, test ]
    uses: russoale/action-test/.github/workflows/deploy.yml@test
    with:
      sha: ${{ github.sha }}
      env: beta
      branch: master
      e2e: true
