name: Test

on:
  - push

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: echo "run tests"

      - name: Deploy to test
        uses: russoale/action-test/.github/workflows/deploy.yml@test
        with:
          env: test
          branch: test
          e2e: true
      
      - name: Deploy to si
        uses: russoale/action-test/.github/workflows/deploy.yml@test
        with:
          env: si
          branch: si
          e2e: false

      - name: Deploy to test
        uses: russoale/action-test/.github/workflows/deploy.yml@test
        with:
          env: main
          branch: main
          e2e: true
