name: Deploy

on:
  workflow_call:
    inputs:
      sha:
        description: "SHA specifying the docker image tag"
        required: true
        type: string
      env:
        description: "Test env to which should be deployed"
        required: true
        type: string
      branch:
        description: "Branch which should be deployed"
        default: "develop"
        required: false
        type: string
      e2e:
        description: "Set to true to run end to end tests after deployment"
        default: false
        required: false
        type: boolean
  repository_dispatch:
    types:
      - delpoy-asset

jobs:

  config:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
      env: ${{ steps.env.outputs.env }}
      branch: ${{ steps.branch.outputs.branch }}
      e2e: ${{ steps.e2e.outputs.e2e }}
    steps:
      - name: Determine SHA
        id: sha
        run: >
          if [[ ${{ github.event_name }} == 'repository_dispatch' ]];
          then echo "##[set-output name=sha;]$(echo "ASSET")";
          else echo "##[set-output name=sha;]$(echo ${{inputs.sha}})";
          fi
      
      - name: Determine env
        id: env
        run: >
          if [[ ${{ github.event_name }} == 'repository_dispatch' ]];
          then echo "##[set-output name=env;]$(echo ${{github.event.client_payload.env}})";
          else echo "##[set-output name=env;]$(echo ${{inputs.env}})";
          fi

      - name: Determine branch
        id: branch
        run: >
          if [[ ${{ github.event_name }} == 'repository_dispatch' ]];
          then echo "##[set-output name=branch;]$(echo ${{github.event.client_payload.branch}})";
          else echo "##[set-output name=branch;]$(echo ${{inputs.branch}})";
          fi

      - name: Determine e2e
        id: e2e
        if: !${{inputs.e2e}}
        run: >
          if [[ ${{ github.event_name }} == 'repository_dispatch' ]];
          then echo "##[set-output name=e2e;]$(echo ${{github.event.client_payload.e2e}})";
          else echo "##[set-output name=e2e;]$(echo ${{inputs.e2e}})";
          fi

  delpoy-asset:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    needs: config
    environment: ${{ needs.config.outputs.env }}
    steps:
      - name: sha
        run: echo "${{ needs.config.outputs.sha }}"
      
      - name: env
        run: |
          echo "${{ needs.config.outputs.env }}"
          echo $ECHO
        env:
          ECHO: ${{ secrets.ECHO }}

      - name: branch
        run: echo "${{ needs.config.outputs.branch }}"

      - name: e2e
        run: echo "${{ needs.config.outputs.e2e }}"


  delpoy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: config
    environment: ${{ needs.config.outputs.env }}
    steps:
      - name: sha
        run: echo "${{ needs.config.outputs.sha }}"
      
      - name: env
        run: |
          echo "${{ needs.config.outputs.env }}"
          echo $ECHO
        env:
          ECHO: ${{ secrets.ECHO }}

      - name: branch
        run: echo "${{ needs.config.outputs.branch }}"

      - name: e2e
        run: echo "${{ needs.config.outputs.e2e }}"
  
  e2e:
    runs-on: ubuntu-latest
    needs: [ delpoy-asset, delpoy]
    environment: ${{ needs.config.outputs.env }}
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled') && 
      needs.config.outputs.e2e == 'true'
    steps:
      - name: e2e
        run: echo "run e2e"